### PR TITLE
Add Fortran to the list of languages.

### PR DESCRIPTION
**Pull request by cfeckardt**
I find it ridiculous that recruiters require that you have 65 years experience of Fortran, when it's only been out for 62 years.

### CODE REVIEW

**Comment by jsrn** [comment]
This PR appears to remove a few of the other entries as well. Could I trouble you to adjust that commit? Thanks!

**Comment by cfeckardt** [comment]
> This PR appears to remove a few of the other entries as well. Could I trouble you to adjust that commit? Thanks!

Oooops

**Comment by cfeckardt** [comment]
@jsrn I have amended the commit, so now there is no evidence of my booboo anymore.

**Comment by jsrn** [comment]
We have buried the evidence.

**Pull request merged**
