### PR TITLE
Add SVN (Subversion)

### PR DESCRIPTION
**Pull request by ph-One**

### CODE REVIEW

**Comment by ph-One** [comment]
Not sure if this should be under, "subversion", or "SVN"...

**Comment by ph-One** [comment]
I agree with using 'Subversion'. Prefixing with 'Apache' wouldn't be consistent with other tooling, such as Cassandra (and other Apache products that _do not_ have the prefix.) :beers:

**Comment by ph-One** [comment]
It's a mixed bag out there for the use of 'Apache'. Your call, sir.

**Comment by Esteban-Rocha** [comment]
Awesome, looks great thank you!

**Pull request merged**
